### ISSUE TITLE
no reconnect after error

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bugzilla2fedmsg#19]
The openshift pod version seems to not reconnect after errors. 

```
Disconnected: Connection closed [[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ss[1/1924$
)]                                                                                                        
Exception in thread Thread-46600:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 97, in _write
    self._socket.sendall(data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/app-root/src/bugzilla2fedmsg/consumer.py", line 99, in _send_heartbeat
    self.stomp.beat()
  File "/opt/app-root/lib/python3.6/site-packages/stompest/util/__init__.py", line 18, in __checkattr
    return f(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/client.py", line 411, in beat
    self.sendFrame(self.session.beat())
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/client.py", line 340, in sendFrame
    self._transport.send(frame)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 82, in send
    self._write(binaryType(frame))
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 99, in _write
    raise StompConnectionError('Could not send to connection [%s]' % e)
stompest.error.StompConnectionError: Could not send to connection [[Errno 14] Bad address]

[bugzilla2fedmsg.consumer DEBUG] STOMP consumer is connecting...
Traceback (most recent call last):
  File "/opt/app-root/bin/bugzilla2fedmsg", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/src/bugzilla2fedmsg/__init__.py", line 33, in cli
    consumer.consume()
  File "/opt/app-root/src/bugzilla2fedmsg/consumer.py", line 70, in consume
    self.stomp.subscribe(self._queue_name, headers)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/util/__init__.py", line 18, in __checkattr
    return f(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/client.py", line 177, in subscribe
    frame, token = self.session.subscribe(destination, headers, receipt)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/protocol/session.py", line 128, in subscribe
    raise StompProtocolError('Already subscribed [%s=%s]' % token)
stompest.error.StompProtocolError: Already subscribed [id=0]
[fedora_messaging.twisted.protocol INFO] Waiting for 0 consumer(s) to finish processing before halting
[fedora_messaging.twisted.protocol INFO] Finished canceling 0 consumers
[fedora_messaging.twisted.protocol INFO] Disconnect requested, but AMQP connection already gone
```

restarting the pod reconnects fine, but it would be very nice if it could keep retrying to connect so we don't have to manually restart it. :)

**Comment by nirik** [comment]
CC: @abompard

**Comment by abompard** [comment]
Hmm I wonder if the failover configuration is wrong somehow, or if the backup address is what causing the issue. I'll do some tests, but unfortunately I can only do them in prod :-/

**Comment by abompard** [comment]
That's it! Prod can't reach `messaging-devops-broker02`. I'll remove it from the config. @nirik do you think we should open a ticket to get access to it?

**Comment by nirik** [comment]
Yep. I can file a ticket on it. Is it just giving connection refused, or just hanging?

**Comment by abompard** [comment]
Connection refused.

**Comment by abompard** [comment]
I now see this in the log:

```
Disconnected: Could not send to connection [[Errno 104] Connection reset by peer]
Exception in thread Thread-5290:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 97, in _write
    self._socket.sendall(data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/app-root/src/bugzilla2fedmsg/consumer.py", line 99, in _send_heartbeat
    self.stomp.beat()
  File "/opt/app-root/lib/python3.6/site-packages/stompest/util/__init__.py", line 18, in __checkattr
    return f(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/client.py", line 411, in beat
    self.sendFrame(self.session.beat())
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/client.py", line 340, in sendFrame
    self._transport.send(frame)
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 82, in send
    self._write(binaryType(frame))
  File "/opt/app-root/lib/python3.6/site-packages/stompest/sync/transport.py", line 99, in _write
    raise StompConnectionError('Could not send to connection [%s]' % e)
stompest.error.StompConnectionError: Could not send to connection [[Errno 32] Broken pipe]

[bugzilla2fedmsg.consumer DEBUG] STOMP consumer is connecting...
Disconnected: Already connected to messaging-devops-broker01.dist.prod.ext.phx2.redhat.com:61612
[bugzilla2fedmsg.consumer DEBUG] STOMP consumer is connecting...
Disconnected: Already connected to messaging-devops-broker01.dist.prod.ext.phx2.redhat.com:61612
[bugzilla2fedmsg.consumer DEBUG] STOMP consumer is connecting...
Disconnected: Already connected to messaging-devops-broker01.dist.prod.ext.phx2.redhat.com:61612
[bugzilla2fedmsg.consumer DEBUG] STOMP consumer is connecting...
[...]
```
And it's not processing messages. I'll investigate.

**Comment by abompard** [comment]
Hopefully I fixed it this time. I'll deploy the patch to prod.

**Comment by nirik** [comment]
So, this is fixed on our side? Or was there still a problem connecting to the 02 broker?
There's still a open internal ticket, they say everything looks ok to them, but they note that only one of the 2 will be accepting connections at any time.
